# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  config: classpath:log4j2/log4j2-spring.xml
  level:
    cn.jay.repository: trace

## Spring配置
spring:
  #数据源基本信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: qcc123
    password: Llx971018
    url: jdbc:mysql://rm-bp12511328i86899l7o.mysql.rds.aliyuncs.com:3306/datacenter?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    druid:
      #连接池属性
      initial-size: 15
      max-active: 100
      min-idle: 15
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1
      validation-query-timeout: 1000
      keep-alive: true
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      use-global-data-source-stat: true
      maxOpenPreparedStatements: 100
      connect-properties.mergeSql: true
      connect-properties.slowSqlMillis: 5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.0.1
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
        # 新版需要配置这个属性才能访问监控页面
        enabled: true
      connection-properties: druid.stat.mergesql\=true;druid.stat.slowsqlmillis\=5000
  ## 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  ## 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  ## rabbitmq配置
  rabbitmq:
    host: qinccy.com
    port: 5672
    username: admin
    password: 971018
    publisher-confirm-type: correlated
    publisher-returns: true
  ## redis配置
  redis:
    host: qinccy.com
    port: 6379
    # 数据库起始索引
    database: 0
    # 连接超时时间（毫秒）
    connect-timeout: 18000000
    lettuce:
      # 数据池配置
      pool:
        # 最大连接数
        max-active: 20
        # 最大阻塞等待时间（负数便是没限制）
        max-wait: 1
        # 最大空闲连接
        max-idle: 5
        # 最小空闲连接
        min-idle: 0
  ## 静态资源配置
  mvc:
    static-path-pattern: /res/**
  resources:
    static-locations: classpath:haha/


# Swagger配置
swagger:
  application-title: "白日梦想家API文档"
  application-description: "这是一个详细介绍"
  email: "liulingxi97@163.com"
  enable: true
  name: "qincc"
  application-version: "v1.0.0"

# MyBatis配置
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.luftmensch.**.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*.xml
  # 加载全局的配置文件
  config-location: classpath:mybatis/mybatis-config.xml


